name: Duplocloud
description: Install Duplocloud tools and login.
author: duplocloud
branding:
  icon: cloud
  color: orange
inputs:
  mask-account-id:
    description: Mask AWS Account ID in logs
    required: false
    default: 'yes'
  region: 
    required: false
    description: Overide the cloud region from the default. For gcp this is required.  
  account-id: 
    required: false
    description: Overide the cloud account id from the default. Required when on gcp where this would be the project name. 
  credentials: 
    required: false
    description: Cloud credentials for Azure or GCP.
  version: 
    required: false
    description: The version of the duploctl to install.
    default: '0.2.49'
  admin:
    required: false
    description: Admin user name.
    default: "false"
  python-version:
    required: false
    description: Python version to install.
    default: "3.12"
  from-source:
    required: false
    description: Install from source using the version as the git ref.
    default: "false"
  python-architecture:
    description: "The target architecture (x86, x64, arm64) of the Python or PyPy interpreter."
    default: "x64"
runs:
  using: composite
  steps:

  - name: Setup Python
    uses: actions/setup-python@v5
    with:
      python-version: ${{ inputs.python-version }}
      architecture: ${{ inputs.python-architecture }}

  - name: Pip Upgrade
    shell: bash
    run: pip install --upgrade pip

  - name: Install duploctl
    id: install-duploctl
    shell: bash
    env:
      VERSION: ${{ inputs.version }}
      FROM_SOURCE: ${{ inputs.from-source }}
    run: |
      PACKAGE=""
      # if from source is true then package is a git url otherwise just duplocloud-client
      if [[ "$FROM_SOURCE" == 'true' ]]; then
        # if the version is latest then reset the value to main
        if [[ "$VERSION" == "latest" ]]; then
          VERSION="main"
        fi
        PACKAGE="git+https://github.com/duplocloud/duploctl.git@${VERSION}"
      else 
        if [[ "$VERSION" == "latest" ]]; then
          PACKAGE="duplocloud-client"
        else
          PACKAGE="duplocloud-client==$VERSION"
        fi
      fi
      pip install $PACKAGE
      
  - name: Duplo Version
    id: duplo-version
    shell: bash
    run: |
      echo "Successfully installed duploctl"
      duploctl version

  - name: Portal Info
    id: portal-info
    shell: bash
    env:
      DUPLO_ACCOUNT_ID: ${{ inputs.account-id }}
      DUPLO_DEFAULT_REGION: ${{ inputs.region }}
      ISADMIN: ${{ inputs.admin }}
    run: $GITHUB_ACTION_PATH/setup/portal-info.sh

  ###
  # AWS Configuration Flow
  ###

  - name: Install AWS CLI
    id: setup-aws-cli
    if: env.AWS_ENABLED == 'true'
    uses: unfor19/install-aws-cli-action@v1

  - name: Duplo JIT for AWS
    id: duplo-jit-aws
    shell: bash
    if: env.AWS_ENABLED == 'true'
    env:
      AWS_REGION: ${{ inputs.region }}
      ADMIN_FLAG: ${{ steps.portal-info.outputs.ADMIN_FLAG }}
    run: >-
      duploctl jit aws -q '{
      AWS_ACCESS_KEY_ID: AccessKeyId, 
      AWS_SECRET_ACCESS_KEY: SecretAccessKey, 
      AWS_SESSION_TOKEN: SessionToken, 
      AWS_REGION: Region
      }' -o env $ADMIN_FLAG >> $GITHUB_OUTPUT

  - name: Configure AWS IAM Credentials
    id: aws-iam
    uses: aws-actions/configure-aws-credentials@v4
    if: env.AWS_ENABLED == 'true'
    with:
      aws-access-key-id: ${{ steps.duplo-jit-aws.outputs.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ steps.duplo-jit-aws.outputs.AWS_SECRET_ACCESS_KEY }}
      aws-session-token: ${{ steps.duplo-jit-aws.outputs.AWS_SESSION_TOKEN }}
      aws-region: ${{ env.AWS_REGION || steps.duplo-jit-aws.outputs.AWS_REGION }}
      mask-aws-account-id: ${{ inputs.mask-account-id }}

  ###
  # GCP Configuration Flow
  ###

  # CLOUDSDK_AUTH_ACCESS_TOKEN: join('',['::add-mask::',Token]), 
  - name: Duplo JIT for GCP
    id: duplo-jit-gcp
    shell: bash
    if: env.GCP_ENABLED == 'true' && !inputs.credentials
    env:
      CLOUDSDK_COMPUTE_REGION: ${{ inputs.region || env.DUPLO_DEFAULT_REGION }}
    run: |
      duploctl jit gcp -q "{
      CLOUDSDK_AUTH_ACCESS_TOKEN: Token, 
      CLOUDSDK_CORE_PROJECT: ProjectId,
      CLOUDSDK_PROJECT: ProjectId,
      GCP_PROJECT: ProjectId,
      GCLOUD_PROJECT: ProjectId,
      GOOGLE_CLOUD_PROJECT: ProjectId,
      CLOUDSDK_COMPUTE_REGION: '${CLOUDSDK_COMPUTE_REGION}'
      }" -o env >> gcp-env.txt
      source gcp-env.txt
      echo "::add-mask::$CLOUDSDK_AUTH_ACCESS_TOKEN"
      cat gcp-env.txt >> $GITHUB_ENV
      rm gcp-env.txt

  - name: Authenticate to Google Cloud
    id: login-gcp
    uses: google-github-actions/auth@v2
    if: env.GCP_ENABLED == 'true' && inputs.credentials
    with:
      credentials_json: ${{ inputs.credentials }}
      export_environment_variables: true

  - name: Set up Cloud SDK
    id: setup-gcloud
    uses: google-github-actions/setup-gcloud@v2
    if: env.GCP_ENABLED == 'true'
    with:
      version: '>= 363.0.0'

  - name: GCloud Info
    id: gcloud-info
    shell: bash
    if: env.GCP_ENABLED == 'true'
    run: |
      gcloud info

  ###
  # Azure Configuration Flow
  ###

  - name: Azure Login
    id: login-azure
    uses: azure/login@v2
    if: env.AZURE_ENABLED == 'true' && inputs.credentials
    with:
      creds: ${{ inputs.credentials }}

  - name: Azure CLI script
    id: setup-azure-cli
    uses: azure/CLI@v2
    if: env.AZURE_ENABLED == 'true' && inputs.credentials
    with:
      azcliversion: 2.57.0
      inlineScript: |
        az account show
