name: Execute Terraform
description: Execute a Terraform command
inputs:
  module:
    description: Working directory
    required: true
  workspace:
    description: Terraform workspace
    required: false
    default: default
  command:
    description: Terraform command
    required: true
    default: plan
  parallelism:
    description: Terraform parallelism
    required: false
  config:
    description: Terraform configs
    required: false
    default: config
runs:
  using: composite
  steps:

  - name: Verify Command
    id: verify-command
    shell: bash
    if: '!contains(fromJSON(''["apply", "destroy", "plan"]''), inputs.command)'
    run: |
      echo "Invalid command: ${{ inputs.command }}"
      echo "Valid commands: apply, destroy, plan"
      exit 1
  
  - name: Setup
    id: setup
    shell: bash
    working-directory: ${{ inputs.module }}
    env:
      TF_WORKSPACE: ${{ inputs.workspace }}
      TF_COMMAND: ${{ inputs.command }}
      TF_PARALLELISM: ${{ inputs.parallelism }}
      MODULE: ${{ inputs.module }}
      CONFIG_DIR: ${{ github.workspace }}/${{ inputs.config }}
    run: |
      ARGS=(
        -input=false
      )
      MODULE_NAME=$(basename $MODULE)
      PLAN_FILE="${TF_WORKSPACE}-${MODULE_NAME}.tfplan"
      echo "module_name=$MODULE_NAME" >> $GITHUB_OUTPUT

      # if parallelism is set then add it to the args
      if [ -n "$TF_PARALLELISM" ]; then
        ARGS+=("-parallelism=$TF_PARALLELISM")
      fi

      # append workspace variables files if they exist
      TF_VARS_FILE="$CONFIG_DIR/$TF_WORKSPACE/$MODULE_NAME.tfvars"
      echo "Discovering vars at $TF_VARS_FILE"
      if [ -f "$TF_VARS_FILE" ]; then
        echo "Found $TF_VARS_FILE"
        ARGS+=("-var-file=$TF_VARS_FILE")
      fi
      echo "Discovering vars at $TF_VARS_FILE.json"
      if [ -f "$TF_VARS_FILE.json" ]; then
        echo "Found $TF_VARS_FILE.json"
        ARGS+=("-var-file=$TF_VARS_FILE.json")
      fi
      
      # if the plan is to destroy then add -destroy to the args
      if [ "$TF_COMMAND" == "destroy" ]; then
        ARGS+=("-destroy")
        PLAN_FILE="${TF_COMMAND}-${PLAN_FILE}"
      fi

      echo "The tf args: ${ARGS[*]}"
      echo "PLAN_FILE=$PLAN_FILE" >> $GITHUB_ENV
      echo "args=${ARGS[*]}" >> $GITHUB_OUTPUT
  
  - name: Select Workspace
    id: select-workspace
    shell: bash
    working-directory: ${{ inputs.module }}
    run: terraform workspace select -or-create ${{ inputs.workspace }}
  
  - name: Check if Plan Exists
    id: archived-plan
    continue-on-error: true
    uses: actions/download-artifact@v3
    with:
      name: ${{ env.PLAN_FILE }}
      path: ${{ inputs.module }}
  
  - name: Plan Module
    id: plan
    shell: bash
    working-directory: ${{ inputs.module }}
    if: steps.archived-plan.outcome == 'failure'
    env:
      TF_ARGS: ${{ steps.setup.outputs.args }}
    run: terraform plan $TF_ARGS -out=$PLAN_FILE
  
  - name: Show Plan
    id: show
    shell: bash
    working-directory: ${{ inputs.module }}
    if: |
      steps.archived-plan.outcome == 'success'
    run: terraform show $PLAN_FILE
  
  - name: Archive Plan
    id: archive-plan
    if: |
      steps.archived-plan.outcome == 'failure'
    uses: actions/upload-artifact@v3
    with:
      name: ${{ env.PLAN_FILE }}
      path: ${{ inputs.module }}/${{ env.PLAN_FILE }}
  
  - name: Apply Module Plan
    id: apply
    shell: bash
    working-directory: ${{ inputs.module }}
    if: inputs.command == 'apply' || inputs.command == 'destroy'
    run: terraform apply -input=false -auto-approve $PLAN_FILE
