name: Run DuploCloud Job
description: Runs a Kubernetes job using duploctl and waits for completion
inputs:
  file:
    description: 'The file with the job definition to run'
    default: job.yaml
    required: false
  wait:
    description: 'Wait for the job to complete'
    default: 'true'
    required: false
  loglevel:
    description: 'Log level for duploctl (INFO, WARN, ERROR, DEBUG)'
    default: 'INFO'
    required: false
  # timeout:
  #   description: 'Timeout in seconds for the job'
  #   default: '300'
  #   required: false
    
runs:
  using: composite
  steps:
  - name: Run Job
    id: duploctl-job
    shell: bash
    env:
      JOB_FILE: ${{ inputs.file }}
      WAIT: ${{ inputs.wait }}
      LOGLEVEL: ${{ inputs.loglevel }}
      # TIMEOUT: ${{ inputs.timeout }}
    run: |
      # Construct command in an array to prevent injection
      cmd_args=("duploctl" "job" "create" "-f" "${JOB_FILE}")
  
      # Add wait flag if specified
      if [[ "${WAIT}" == "true" ]]; then
        cmd_args+=("--wait")
      fi
  
      # Add log level if specified
      if [[ -n "${LOGLEVEL}" ]]; then
        cmd_args+=("--loglevel" "${LOGLEVEL}")
      fi
  
      # # Add timeout if specified - Not yet implemented in CLI
      # if [[ -n "${TIMEOUT}" ]]; then
      #   cmd_args+=("--timeout" "${TIMEOUT}")
      # fi
  
      echo "Running command: ${cmd_args[*]}"
      "${cmd_args[@]}"