name: 'AI HelpDesk Ticket'
description: 'Creates a HelpDesk ticket for AI analysis when workflows fail'
author: 'duplocloud'
branding:
  icon: 'ticket'
  color: 'blue'
inputs:
  title:
    description: 'Custom ticket title. If not provided, defaults to "Workflow Failure: {workflow_name}"'
    required: false
    default: ''
  context:
    description: Custom contextual header content. If not provided, auto-generates workflow context
    required: false
    default: ''
  content:
    description: Main ticket content/body. Appended to context if provided
    required: false
    default: ''
  include_sensitive_data:
    description: Whether to include sensitive data (repository, actor, branch, commit) in ticket context
    required: false
    default: 'true'

outputs:
  ticket_id:
    description: The created ticket ID
    value: ${{ steps.create-ticket.outputs.ticket_id }}
  ticket_url:
    description: The URL to the created ticket
    value: ${{ steps.create-ticket.outputs.ticket_url }}

runs:
  using: composite
  steps:

  - name: Create HelpDesk Ticket
    id: create-ticket
    shell: bash
    env:
      TITLE: ${{ inputs.title }}
      CONTEXT: ${{ inputs.context }}
      CONTENT: ${{ inputs.content }}
      INCLUDE_SENSITIVE_DATA: ${{ inputs.include_sensitive_data }}
    run: |
      # Validate required environment variables
      if [ -z "$DUPLO_HOST" ] || [ -z "$DUPLO_TOKEN" ] || [ -z "$DUPLO_TENANT" ]; then
        echo "Error: Required environment variables DUPLO_HOST, DUPLO_TOKEN, and DUPLO_TENANT must be set"
        echo "Please ensure the Duplo Setup action is run before this action"
        exit 1
      fi

      # Validate duploctl is available
      if ! command -v duploctl &> /dev/null; then
        echo "Error: duploctl command not found"
        echo "Please ensure the Duplo Setup action is run before this action"
        exit 1
      fi

      # Build title
      if [ -n "$TITLE" ]; then
        TICKET_TITLE="$TITLE"
      else
        TICKET_TITLE="Workflow Failure: ${GITHUB_WORKFLOW:-Unknown Workflow}"
      fi

      # Build context
      if [ -n "$CONTEXT" ]; then
        TICKET_CONTEXT="$CONTEXT"
      else
        TICKET_CONTEXT="GitHub Actions workflow failure detected!"$'\n\n'"Workflow Details:"
        [ -n "$GITHUB_WORKFLOW" ] && TICKET_CONTEXT="$TICKET_CONTEXT"$'\n'"- Workflow: $GITHUB_WORKFLOW"
        [ -n "$GITHUB_RUN_ID" ] && TICKET_CONTEXT="$TICKET_CONTEXT"$'\n'"- Run ID: $GITHUB_RUN_ID"
        [ -n "$GITHUB_EVENT_NAME" ] && TICKET_CONTEXT="$TICKET_CONTEXT"$'\n'"- Event: $GITHUB_EVENT_NAME"

        if [ "$INCLUDE_SENSITIVE_DATA" = "true" ]; then
          [ -n "$GITHUB_REPOSITORY" ] && TICKET_CONTEXT="$TICKET_CONTEXT"$'\n'"- Repository: $GITHUB_REPOSITORY"
          [ -n "$GITHUB_SHA" ] && TICKET_CONTEXT="$TICKET_CONTEXT"$'\n'"- Commit: $GITHUB_SHA"
          [ -n "$GITHUB_ACTOR" ] && TICKET_CONTEXT="$TICKET_CONTEXT"$'\n'"- Actor: $GITHUB_ACTOR"
          [ -n "$GITHUB_REF_NAME" ] && TICKET_CONTEXT="$TICKET_CONTEXT"$'\n'"- Branch: $GITHUB_REF_NAME"
          if [ -n "$GITHUB_REPOSITORY" ] && [ -n "$GITHUB_RUN_ID" ]; then
            TICKET_CONTEXT="$TICKET_CONTEXT"$'\n'"- Run URL: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          fi
        fi

        # Add fallback content if no GitHub vars
        if [ -z "$GITHUB_WORKFLOW$GITHUB_RUN_ID$GITHUB_EVENT_NAME" ]; then
          TICKET_CONTEXT="$TICKET_CONTEXT"$'\n'"- Source: Manual execution or testing environment"
        fi

        TICKET_CONTEXT="$TICKET_CONTEXT"$'\n\n'
      fi

      # Build final message
      if [ -n "$CONTENT" ]; then
        TICKET_MESSAGE="$TICKET_CONTEXT$CONTENT"
      else
        TICKET_MESSAGE="$TICKET_CONTEXT"
      fi

      # Create the ticket
      duploctl ai create_ticket \
        --title "$TICKET_TITLE" \
        --agent_name "$AGENT_NAME" \
        --instance_id "$AGENT_INSTANCE" \
        --message "$TICKET_MESSAGE" > response.txt 2>&1 &

      wait
      EXIT_CODE=$?

      # Read the response
      RESPONSE=$(cat response.txt)
      rm -f response.txt

      if [ $EXIT_CODE -eq 0 ] && ! echo "$RESPONSE" | grep -q "Error\|Message.*Error"; then
        echo "Ticket created successfully"

        # Extract ticket ID and URL from response
        TICKET_ID=$(echo "$RESPONSE" | grep -o '"ticketname": "[^"]*"' | cut -d'"' -f4)
        TICKET_URL=$(echo "$RESPONSE" | grep -o '"chat_url": "[^"]*"' | cut -d'"' -f4)

        # Set outputs
        echo "ticket_id=$TICKET_ID" >> $GITHUB_OUTPUT
        echo "ticket_url=$TICKET_URL" >> $GITHUB_OUTPUT

        echo "Ticket ID: $TICKET_ID"
        echo "Ticket URL: $TICKET_URL"
      else
        echo "Failed to create ticket"
        echo "Error: $RESPONSE"
        echo ""
        echo "Configuration:"
        echo "  DUPLO_HOST: $DUPLO_HOST"
        echo "  DUPLO_TENANT: $DUPLO_TENANT"
        echo "  AGENT_NAME: $AGENT_NAME"
        echo "  AGENT_INSTANCE: $AGENT_INSTANCE"

        exit 1
      fi
