name: Tag Image
description: Tag the image used by a service in a sepcific tenant. 
inputs:
  name: 
    description: The name of the service
    required: true
  tags: 
    description: The tags to apply to the image
    required: false
runs:
  using: composite
  steps:

  - name: Tag Image
    id: tag
    shell: bash
    env:
      SERVICE_NAME: ${{ inputs.name }}
      TAGS_INPUT: ${{ inputs.tags }}
    run: $GITHUB_ACTION_PATH/tag-image.sh
