name: Duplo AWS Setup
description: Install Duplo and AWS tools and login.
inputs:
  mask-aws-account-id:
    description: Mask AWS Account ID in logs
    required: false
    default: 'yes'
runs:
  using: composite
  steps:

  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'

  - name: Install duploctl
    id: install-duploctl
    shell: bash
    run: |
      pip install duplocloud-client

  - name: Portal Info
    id: portal-info
    shell: bash
    run: |
      export PORTAL_INFO AWS_ENABLED
      PORTAL_INFO="$(duploctl system info)"

      AWS_ENABLED="$(echo "$PORTAL_INFO" | jq -r '.IsAwsCloudEnabled')"
      GCP_ENABLED="$(echo "$PORTAL_INFO" | jq -r '.IsGoogleCloudEnabled')"
      AZURE_ENABLED="$(echo "$PORTAL_INFO" | jq -r '.IsAzureCloudEnabled')"

      echo "AWS_ENABLED=$AWS_ENABLED" >> $GITHUB_ENV
      echo "GCP_ENABLED=$GCP_ENABLED" >> $GITHUB_ENV
      echo "AZURE_ENABLED=$AZURE_ENABLED" >> $GITHUB_ENV

  - name: Install AWS CLI
    id: install-aws-cli
    if: env.AWS_ENABLED == 'true'
    uses: unfor19/install-aws-cli-action@v1

  - name: Duplo JIT for AWS
    id: duplo-jit-aws
    shell: bash
    if: env.AWS_ENABLED == 'true'
    run: |
      export STS AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_DEFAULT_REGION AWS_REGION AWS_ACCOUNT_ID

      STS="$(duploctl jit aws)"
      AWS_ACCESS_KEY_ID="$(echo "$STS" | jq -r '.AccessKeyId')"
      AWS_SECRET_ACCESS_KEY="$(echo "$STS" | jq -r '.SecretAccessKey')"
      AWS_SESSION_TOKEN="$(echo "$STS" | jq -r '.SessionToken')"
      AWS_DEFAULT_REGION="$(echo "$STS" | jq -r '.Region')"
      AWS_REGION="$AWS_DEFAULT_REGION"
      AWS_ACCOUNT_ID="$(aws sts get-caller-identity --query "Account" --output text)"

      echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_OUTPUT
      echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_OUTPUT
      echo "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" >> $GITHUB_OUTPUT
      echo "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION" >> $GITHUB_OUTPUT
      echo "AWS_REGION=$AWS_REGION" >> $GITHUB_OUTPUT
      echo "AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID" >> $GITHUB_OUTPUT

  - # alternative login. Useful when running act locally with ACT_AWS_SESSION
    name: Configure AWS IAM Credentials
    id: aws-iam
    uses: aws-actions/configure-aws-credentials@v2
    if: env.AWS_ENABLED == 'true'
    with:
      aws-access-key-id: ${{ steps.duplo-jit-aws.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ steps.duplo-jit-aws.AWS_SECRET_ACCESS_KEY }}
      aws-session-token: ${{ steps.duplo-jit-aws.AWS_SESSION_TOKEN }}
      aws-region: ${{ steps.duplo-jit-aws.AWS_REGION }}
      mask-aws-account-id: ${{ inputs.mask-aws-account-id }}
