name: AWS Login
description: Login to AWS with duplo creds
runs:
  using: composite
  steps:

  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'

  - name: Install duploctl
    uses: BSFishy/pip-action@v1
    with:
      packages: |
        duplocloud-client

  - name: Install AWS CLI
    id: install-aws-cli
    uses: unfor19/install-aws-cli-action@v1

  - name: Duplo JIT for AWS
    shell: bash
    run: |
      export STS AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_DEFAULT_REGION AWS_REGION AWS_ACCOUNT_ID

      STS="$(duploctl jit aws)"
      AWS_ACCESS_KEY_ID="$(echo "$STS" | jq -r '.AccessKeyId')"
      AWS_SECRET_ACCESS_KEY="$(echo "$STS" | jq -r '.SecretAccessKey')"
      AWS_SESSION_TOKEN="$(echo "$STS" | jq -r '.SessionToken')"
      AWS_DEFAULT_REGION="$(echo "$STS" | jq -r '.Region')"
      AWS_REGION="$AWS_DEFAULT_REGION"
      AWS_ACCOUNT_ID="$(aws sts get-caller-identity --query "Account" --output text)"

      cat <<EOF >> $GITHUB_ENV
      AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
      AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      AWS_REGION=$AWS_REGION
      AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
      EOF

  - # alternative login. Useful when running act locally with ACT_AWS_SESSION
    name: Configure AWS IAM Credentials
    id: aws-iam
    uses: aws-actions/configure-aws-credentials@v2
    with:
      aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
      aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
      aws-region: ${{ env.AWS_REGION }}
